# Generated by Django 6.0.1 on 2026-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_result_mission_label_alter_result_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('intro', models.TextField()),
                ('body_1', models.TextField()),
                ('body_2', models.TextField()),
                ('body_3', models.TextField()),
                ('conclusion', models.TextField()),
                ('deep_dive', models.TextField(blank=True)),
                ('deep_dive_extra', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
