# Generated by Django 6.0.1 on 2026-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='og_image_url',
            field=models.URLField(blank=True),
        ),
    ]
