# Generated by Django 6.0.1 on 2026-02-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_blogpost_og_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('placement', models.CharField(choices=[('header', '헤더'), ('intro', '서론'), ('body1', '본론 1'), ('body2', '본론 2'), ('body3', '본론 3'), ('conclusion', '결론'), ('deep_dive', '추가 인사이트')], default='body1', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quiz.blogpost')),
            ],
            options={
                'ordering': ['placement', 'order', 'id'],
            },
        ),
    ]
