# Generated by Django 6.0.1 on 2026-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_type_a',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type_b',
            field=models.CharField(default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type_c',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type_d',
            field=models.CharField(default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='result',
            name='share_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_results/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_thumbs/'),
        ),
    ]
